export const GET_ATTENTION_DESCRIPTION = [
    'Owner-scoped roll-up of cells worth attention, most time-sensitive first — so you skip scanning the whole',
    'map. Flags, each with a severity: stalled mining/craft (the output box has room for less than one whole',
    'cycle, so nothing settles and the wait burns — critical); a near-full warehouse on an actively-produced',
    'resource, a job that has run its scheduled cycles and now idles the cell until claimed, an arrived delivery',
    'ready to finalize, an extractor on a depleted deposit, or one of your open lots frozen because the hub',
    'raised its live sale fee above your tolerance (buys revert; cancel stays fee-free) (warning);',
    'revealed-but-unbuilt cells, cells in a post-demolish rebuild cooldown, and an open lot whose live sale fee',
    'now sits exactly at your tolerance so the next hike freezes it (info — on a `demolish_cooldown` item',
    '`arrivalAt` marks when rebuild reopens). A finished job loses nothing by waiting, unlike a stall — it only',
    'holds the cell idle. Items are purely descriptive (cell, resource, used/cap breakdown, deposit, delivery,',
    'and for a lot its `lotId`, hub cell and a `message`) and suggest no action — you decide. Lot flags cover',
    'your own open lots only. Your own cells need an authenticated wallet; pass `owner` to scout another player',
    'read-only (all data is public). `minSeverity` filters by urgency. If the deliveries or lots endpoint is',
    'down, map items still return and a `note` says so.',
].join(' ');
