export const GET_MAP_DESCRIPTION = [
    'Read the live game world. The map is loaded at startup and kept current in the background;',
    'this returns a snapshot of it on demand (you only see updates when you call a tool).',
    'The map is public — you can see every player. Resources live on cells.',
    'Always returns a "summary" (counts + freshness) and, when your wallet is known, a "resourceIndex"',
    '(resourceId → your cells holding it, with location). Cells come back as a graph: each carries axial',
    'x/y and "neighbors" (the 6 adjacent hexes, each owned/other/empty).',
    'Scopes: "mine" (your cells), "around" (cells within a hex radius — scout a region),',
    '"cells" (specific tokenIds), "all" (everything), "summary" (no cells). Default: "mine", else "summary".',
    'Note units: version/updated are epoch ms, serverTime/startAt are unix seconds, amounts are decimal strings.',
    'Each cell resource carries a "storage" box — used/cap/reserved/stalled — in the same integer units as',
    'deposit/balance; cap null means uncapped (render ∞). Production stalls when a box is full; trust the',
    'server "stalled" flag rather than recomputing. The summary carries "stalledCells"; use `cpu_get_attention` for',
    'the full owner to-do list.',
    'Also carries "server": { reachable } — false means the game server is unreachable right now and',
    'actions will fail; retry once it is true again.',
].join(' ');
