export const CELL_ABI = [
    {
        type: 'function',
        name: 'requestReveal',
        inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
        outputs: [],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'entropy',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'entropyProvider',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'event',
        name: 'RevealRequested',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'sequenceNumber', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'isGenesis', type: 'bool', indexed: false, internalType: 'bool' },
            { name: 'revealCount', type: 'uint32', indexed: false, internalType: 'uint32' },
        ],
        anonymous: false,
    },
    {
        type: 'function',
        name: 'place',
        inputs: [
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: 'newType', type: 'uint16', internalType: 'uint16' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'demolish',
        inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'startMining',
        inputs: [
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: 'target', type: 'uint16', internalType: 'uint16' },
            { name: 'batches', type: 'uint32', internalType: 'uint32' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'startCraft',
        inputs: [
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: 'recipeId', type: 'uint64', internalType: 'uint64' },
            { name: 'batches', type: 'uint32', internalType: 'uint32' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'claim',
        inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'withdrawCpu',
        inputs: [
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: 'amount', type: 'uint64', internalType: 'uint64' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'event',
        name: 'BuildingPlaced',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'buildingType', type: 'uint16', indexed: false, internalType: 'uint16' },
            { name: 'buildFinishAt', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'inputResources', type: 'uint16[]', indexed: false, internalType: 'uint16[]' },
            { name: 'inputAmounts', type: 'uint64[]', indexed: false, internalType: 'uint64[]' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'BuildingDemolished',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'buildingType', type: 'uint16', indexed: false, internalType: 'uint16' },
            { name: 'demolishFinishAt', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'inputResources', type: 'uint16[]', indexed: false, internalType: 'uint16[]' },
            { name: 'inputAmounts', type: 'uint64[]', indexed: false, internalType: 'uint64[]' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MiningStarted',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'resource', type: 'uint16', indexed: false, internalType: 'uint16' },
            { name: 'durationSec', type: 'uint32', indexed: false, internalType: 'uint32' },
            { name: 'yieldPerCycle', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'batches', type: 'uint32', indexed: false, internalType: 'uint32' },
            { name: 'startAt', type: 'uint64', indexed: false, internalType: 'uint64' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'ResourceMined',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'resource', type: 'uint16', indexed: false, internalType: 'uint16' },
            { name: 'amount', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'drained', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'startAt', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'claimedBatches', type: 'uint32', indexed: false, internalType: 'uint32' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'CraftStarted',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'recipeId', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'batches', type: 'uint32', indexed: false, internalType: 'uint32' },
            { name: 'durationSec', type: 'uint32', indexed: false, internalType: 'uint32' },
            { name: 'startAt', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'inputResources', type: 'uint16[]', indexed: false, internalType: 'uint16[]' },
            { name: 'inputAmounts', type: 'uint64[]', indexed: false, internalType: 'uint64[]' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'CraftClaimed',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'recipeId', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'batches', type: 'uint32', indexed: false, internalType: 'uint32' },
            { name: 'outputResources', type: 'uint16[]', indexed: false, internalType: 'uint16[]' },
            { name: 'outputAmounts', type: 'uint64[]', indexed: false, internalType: 'uint64[]' },
            { name: 'startAt', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'claimedBatches', type: 'uint32', indexed: false, internalType: 'uint32' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'CpuWithdrawn',
        inputs: [
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'to', type: 'address', indexed: true, internalType: 'address' },
            { name: 'amount', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'cpuMinted', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
] as const;
