// The lot marketplace. Trimmed to the writes the client sends plus the events it decodes from the
// receipt; lot state is read from the game API, so no view functions are included. Must match the
// deployed Trade contract.
export const TRADE_ABI = [
    {
        type: 'function',
        name: 'createLot',
        inputs: [
            { name: 'tokenIds', type: 'uint256[]', internalType: 'uint256[]' },
            { name: 'res', type: 'uint16', internalType: 'uint16' },
            { name: 'value', type: 'uint128', internalType: 'uint128' },
            { name: 'price', type: 'uint128', internalType: 'uint128' },
            { name: 'maxFee', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'lotId', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'buy',
        inputs: [
            { name: 'lotId', type: 'uint256', internalType: 'uint256' },
            { name: 'value', type: 'uint128', internalType: 'uint128' },
            { name: 'destTokenIds', type: 'uint256[]', internalType: 'uint256[]' },
            { name: 'maxFee', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'cancel',
        inputs: [
            { name: 'lotId', type: 'uint256', internalType: 'uint256' },
            { name: 'returnTokenIds', type: 'uint256[]', internalType: 'uint256[]' },
            { name: 'maxFee', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'event',
        name: 'LotCreated',
        inputs: [
            { name: 'lotId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'seller', type: 'address', indexed: true, internalType: 'address' },
            { name: 'hub', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'resource', type: 'uint16', indexed: false, internalType: 'uint16' },
            { name: 'value', type: 'uint128', indexed: false, internalType: 'uint128' },
            { name: 'pricePerUnit', type: 'uint128', indexed: false, internalType: 'uint128' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'LotOpened',
        inputs: [
            { name: 'lotId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'remaining', type: 'uint128', indexed: false, internalType: 'uint128' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'LotBought',
        inputs: [
            { name: 'lotId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'buyer', type: 'address', indexed: true, internalType: 'address' },
            { name: 'value', type: 'uint128', indexed: false, internalType: 'uint128' },
            { name: 'remaining', type: 'uint128', indexed: false, internalType: 'uint128' },
            { name: 'sale', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'LotCancelled',
        inputs: [
            { name: 'lotId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'seller', type: 'address', indexed: true, internalType: 'address' },
            { name: 'returned', type: 'uint128', indexed: false, internalType: 'uint128' },
        ],
        anonymous: false,
    },
    { type: 'error', name: 'ZeroAddress', inputs: [] },
    { type: 'error', name: 'PathTooShort', inputs: [] },
    { type: 'error', name: 'InvalidValue', inputs: [] },
    { type: 'error', name: 'InvalidPrice', inputs: [] },
    { type: 'error', name: 'LotTooSmall', inputs: [] },
    { type: 'error', name: 'PriceTooLow', inputs: [] },
    { type: 'error', name: 'NotRevealed', inputs: [] },
    { type: 'error', name: 'NotHub', inputs: [] },
    { type: 'error', name: 'LotNotDelivering', inputs: [] },
    { type: 'error', name: 'WrongResource', inputs: [] },
    { type: 'error', name: 'LotNotOpen', inputs: [] },
    { type: 'error', name: 'NotSeller', inputs: [] },
    { type: 'error', name: 'ExceedsRemaining', inputs: [] },
    { type: 'error', name: 'WrongHub', inputs: [] },
    { type: 'error', name: 'NotDestOwner', inputs: [] },
    { type: 'error', name: 'NotTransport', inputs: [] },
    { type: 'error', name: 'SaleBurnTooHigh', inputs: [] },
] as const;
