export const TRANSPORT_ABI = [
    {
        type: 'function',
        name: 'move',
        inputs: [
            { name: 'xs', type: 'int256[]', internalType: 'int256[]' },
            { name: 'ys', type: 'int256[]', internalType: 'int256[]' },
            { name: 'res', type: 'uint16', internalType: 'uint16' },
            { name: 'amount', type: 'uint64', internalType: 'uint64' },
            { name: 'maxFee', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [
            { name: 'deliveryId', type: 'uint256', internalType: 'uint256' },
            { name: 'arrivalAt', type: 'uint64', internalType: 'uint64' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'quoteRoute',
        inputs: [
            { name: 'from', type: 'address', internalType: 'address' },
            { name: 'xs', type: 'int256[]', internalType: 'int256[]' },
            { name: 'ys', type: 'int256[]', internalType: 'int256[]' },
            { name: 'res', type: 'uint16', internalType: 'uint16' },
            { name: 'amount', type: 'uint64', internalType: 'uint64' },
        ],
        outputs: [
            { name: 'totalFee', type: 'uint256', internalType: 'uint256' },
            { name: 'totalDistance', type: 'uint256', internalType: 'uint256' },
            { name: 'arrivalAt', type: 'uint64', internalType: 'uint64' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'finalizeMany',
        inputs: [{ name: 'ids', type: 'uint256[]', internalType: 'uint256[]' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'getDelivery',
        inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
        outputs: [
            {
                name: '',
                type: 'tuple',
                internalType: 'struct ITransport.Delivery',
                components: [
                    { name: 'receiver', type: 'address', internalType: 'address' },
                    { name: 'targetId', type: 'uint256', internalType: 'uint256' },
                    { name: 'resource', type: 'uint16', internalType: 'uint16' },
                    { name: 'amount', type: 'uint64', internalType: 'uint64' },
                    { name: 'arrivalAt', type: 'uint64', internalType: 'uint64' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'event',
        name: 'DeliveryScheduled',
        inputs: [
            { name: 'deliveryId', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'payer', type: 'address', indexed: true, internalType: 'address' },
            { name: 'sourceId', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'receiver', type: 'address', indexed: false, internalType: 'address' },
            { name: 'targetId', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'resource', type: 'uint16', indexed: false, internalType: 'uint16' },
            { name: 'amount', type: 'uint64', indexed: false, internalType: 'uint64' },
            { name: 'arrivalAt', type: 'uint64', indexed: false, internalType: 'uint64' },
        ],
        anonymous: false,
    },
    { type: 'error', name: 'ZeroAddress', inputs: [] },
    { type: 'error', name: 'ZeroAmount', inputs: [] },
    { type: 'error', name: 'BelowMinAmount', inputs: [] },
    { type: 'error', name: 'ArrayLengthMismatch', inputs: [] },
    { type: 'error', name: 'PathTooShort', inputs: [] },
    { type: 'error', name: 'NotRevealed', inputs: [] },
    { type: 'error', name: 'NotEligibleWaypoint', inputs: [] },
    { type: 'error', name: 'DegenerateWaypoint', inputs: [] },
    { type: 'error', name: 'HopOutOfRange', inputs: [] },
    { type: 'error', name: 'NotWaypointOwner', inputs: [] },
    { type: 'error', name: 'FeeExceedsMax', inputs: [] },
    { type: 'error', name: 'DeliveryNotFound', inputs: [] },
    { type: 'error', name: 'NotYetArrived', inputs: [] },
    { type: 'error', name: 'BurnPercentTooHigh', inputs: [] },
] as const;
